Fix build error by adding missing include: tf2_geometry_msgs.h
Context: Ubuntu 20.04 with ROS Noetic.
While I was trying to catkin build, I was getting cmake errors in follow_path.cpp and follow_topic.cpp like below. 

I found the solution by sheer luck here: https://answers.ros.org/question/239260/tf2_rosbuffertransform-causes-undefined-reference-errors/

/usr/bin/ld: CMakeFiles/flex_nav_planners_follow_topic_node.dir/src/follow_topic.cpp.o: in function `geometry_msgs::PoseStamped_<std::allocator<void> >& tf2_ros::BufferInterface::transform<geometry_msgs::PoseStamped_<std::allocator<void> > >(geometry_msgs::PoseStamped_<std::allocator<void> > const&, geometry_msgs::PoseStamped_<std::allocator<void> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, ros::Duration) const':
follow_topic.cpp:(.text._ZNK7tf2_ros15BufferInterface9transformIN13geometry_msgs12PoseStamped_ISaIvEEEEERT_RKS6_S7_RKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEN3ros8DurationE[_ZNK7tf2_ros15BufferInterface9transformIN13geometry_msgs12PoseStamped_ISaIvEEEEERT_RKS6_S7_RKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEN3ros8DurationE]+0x5c): undefined reference to `ros::Time const& tf2::getTimestamp<geometry_msgs::PoseStamped_<std::allocator<void> > >(geometry_msgs::PoseStamped_<std::allocator<void> > const&)'
/usr/bin/ld: follow_topic.cpp:(.text._ZNK7tf2_ros15BufferInterface9transformIN13geometry_msgs12PoseStamped_ISaIvEEEEERT_RKS6_S7_RKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEN3ros8DurationE[_ZNK7tf2_ros15BufferInterface9transformIN13geometry_msgs12PoseStamped_ISaIvEEEEERT_RKS6_S7_RKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEN3ros8DurationE]+0x6e): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const& tf2::getFrameId<geometry_msgs::PoseStamped_<std::allocator<void> > >(geometry_msgs::PoseStamped_<std::allocator<void> > const&)'
/usr/bin/ld: follow_topic.cpp:(.text._ZNK7tf2_ros15BufferInterface9transformIN13geometry_msgs12PoseStamped_ISaIvEEEEERT_RKS6_S7_RKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEN3ros8DurationE[_ZNK7tf2_ros15BufferInterface9transformIN13geometry_msgs12PoseStamped_ISaIvEEEEERT_RKS6_S7_RKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEN3ros8DurationE]+0xb8): undefined reference to `void tf2::doTransform<geometry_msgs::PoseStamped_<std::allocator<void> > >(geometry_msgs::PoseStamped_<std::allocator<void> > const&, geometry_msgs::PoseStamped_<std::allocator<void> >&, geometry_msgs::TransformStamped_<std::allocator<void> > const&)'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/flex_nav_planners_follow_topic_node.dir/build.make:151: /home/xabi/EGOKITUZLab/devel/.private/flex_nav_planners/lib/flex_nav_planners/flex_nav_planners_follow_topic_node] Error 1
make[1]: *** [CMakeFiles/Makefile2:421: CMakeFiles/flex_nav_planners_follow_topic_node.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
make: *** [Makefile:141: all] Error 2